
package com.mycompany.proyecto_fide_towerdefense;

import static com.mycompany.proyecto_fide_towerdefense.VentanaPrincipal.HEIGHT;
import static com.mycompany.proyecto_fide_towerdefense.VentanaPrincipal.WIDTH;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author valem
 */
public class PantallaDeJuego extends javax.swing.JFrame {

    public static final int WIDTH = 842, HEIGHT = 582; //El tamanio de la ventana
    
    private void AjustarImagen (JLabel labelName, String ruta) {//Para poder colocar imagenes
    ImageIcon imagen = new ImageIcon(ruta);
    Icon icon = new ImageIcon( imagen.getImage().getScaledInstance(
    labelName.getWidth(), labelName.getHeight(), 
    Image.SCALE_DEFAULT));
    labelName.setIcon(icon);
    this.repaint ();
    }
    
    public PantallaDeJuego() {
        initComponents();
        setTitle("Tower Defense");//Para que el nombre de la ventana sea este texto
        setSize(WIDTH, HEIGHT); //Son los atributos de ancho y largo creados arriba para la ventana
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);//Para que la x de la ventana funcione
        setResizable(false);//Para que la pantalla no se pueda redimensionar se mantenga en las medidad estaticas creadas en la linea 12
        setLocationRelativeTo(null);//Para que la ventana se encuentre en el centro de la p'agina
        AjustarImagen(fondo,"src\\main\\java\\Imagenes\\fondojuego.png");//Busca la imagen y la ajusta con el metodo creado arriba
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 836, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
